### PR TITLE
set container per section & fix layout footer

### PR DESCRIPTION
**Pull request by MyFRA**
I have edited many parts on this netflix ui clone,

first, that is on a section by section, here I change it to be like the official from the netflix web, from like this
Screenshot_2021-10-04_00-29-23
to like this
Screenshot_2021-10-04_00-29-56

Second, I also tidy up the footer. I changed it from this
Screenshot_2021-10-04_00-30-42
to like this
Screenshot_2021-10-04_00-31-02

for reference to the official netflix website, it can be seen on the following website https://www.netflix.com/

### CODE REVIEW

**Comment by ahmadsohail404** [comment]
resolve conflicts

**Comment by MyFRA** [comment]
> resolve conflicts

I have fixed the conflict, and made sure the code actually runs properly

**Comment by ahmadsohail404** [comment]
still there is some comflict in styles.css i can see

**Comment by MyFRA** [comment]
I have finished it. Previously I have fixed the conflict, but maybe because of another pull request, so I have to fix this conflict pull request again

**Comment by MyFRA** [comment]
> still there is some comflict in styles.css i can see

Please, can you review my pull request

**Comment by ahmadsohail404** [comment]
you have conflicts in index.html

**Pull request closed without merging**
